[font]
size = 15.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[colors.bright]
black = "#415367"
blue = "#36b2d4"
cyan = "#59dcd8"
green = "#7fdc59"
magenta = "#b759dc"
red = "#dc7759"
white = "#e5ded6"
yellow = "#dcb659"

[colors.cursor]
cursor = "#e5ded6"
text = "#161c23"

[colors.normal]
black = "#555555"
blue = "#36b2d4"
cyan = "#59dcd8"
green = "#59dcb7"
magenta = "#b759dc"
red = "#dc7759"
white = "#abb2bf"
yellow = "#dcb659"

[colors.primary]
background = "#0f1419"
foreground = "#e5ded6"

[colors.selection]
background = "#232d38"
text = "#e5ded6"

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[window]
opacity = 0.95

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[keyboard]
bindings = [
  { key = "H", mods = "Shift", mode = "Vi|~Search", action = "FirstOccupied" },
  { key = "L", mods = "Shift", mode = "Vi|~Search", action = "Last" },
]

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t/=."

[hints]
alphabet = "sadjklewcmpgh"

[[hints.enabled]]
command = "firefox"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[[hints.enabled]]
hyperlinks = false
action = "MoveViModeCursor"
post_processing = true
persist = false
mouse.enabled = false
binding = { key = "o", mode = "Vi|~Search" }
regex = "\\w{2,}"
