[style.description]
underline = false
bold = false
italic = false

[style.command_name]
foreground = { rgb = { r = 28, g = 155, b = 172 } }
underline = false
bold = true
italic = false

[style.example_text]
foreground = { rgb = { r = 191, g = 189, b = 182 } }
underline = false
bold = false
italic = false

[style.example_code]
foreground = { rgb = { r = 32, g = 175, b = 193 } }
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { rgb = { r = 144, g = 164, b = 174 } }
underline = false
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 720
archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/"
tls_backend = "native-tls"
