#!/bin/bash

# ---- repo root check ----
if [ ! -d ".git" ]; then
        echo "Please run this script from the root directory of the dotfiles repository."
    exit 1
fi

# ---- update submodules ----
git submodule update --init --recursive

# ---- helix config and languages config ----
HELIX_CONFIG_DIR="$HOME/.config/helix"
for file in config.toml languages.toml; do
    TARGET="$HELIX_CONFIG_DIR/$file"
    SOURCE="$(pwd)/helix/$file"
    if [[ -L "$TARGET" && "$(readlink "$TARGET")" != "$SOURCE" ]]; then
        rm "$TARGET"
    fi
    if [[ ! -e "$TARGET" ]]; then
        ln -s "$SOURCE" "$TARGET"
        echo "Created symbolic link for $file."
    else
        echo "Symbolic link for $file already exists."
    fi
done

# ---- before oh my zsh script building ----

BEFORE_OHMYZSH_PATH="$(pwd)/zsh/before_ohmyzsh.zsh"

echo "# ---- before oh my zsh source in .zshrc (autogenerated by setup script) ----" > "$BEFORE_OHMYZSH_PATH"

ZSH_CUSTOM_PATH="$(pwd)/zsh/zsh_custom"
echo "ZSH_CUSTOM=$ZSH_CUSTOM_PATH" >> "$BEFORE_OHMYZSH_PATH"

SCRIPTS_PATH="$(pwd)/scripts"
echo "PATH=\"$SCRIPTS_PATH:\$PATH\"" >> "$BEFORE_OHMYZSH_PATH"

DOTFILES_PATH_EXPORT="export DOTFILES_REPO_ROOT=$(pwd)"
echo "$DOTFILES_PATH_EXPORT" >> "$BEFORE_OHMYZSH_PATH"

ENABLED_PLUGINS="zsh-ssh git"
echo "plugins=($ENABLED_PLUGINS \$plugins)" >> "$BEFORE_OHMYZSH_PATH"

echo 'precmd() { print -n "\033[5 q" }' >> "$BEFORE_OHMYZSH_PATH"

# ---- before oh my zsh file insertion ----

SOURCE_OH_MY_ZSH_LINE="source \$ZSH/oh-my-zsh.sh"
SOURCE_BEFORE_OHMYZSH_LINE="source $BEFORE_OHMYZSH_PATH"

if [[ ! -f "$HOME/.zshrc" ]]; then
    echo "Warning: .zshrc file does not exist. Skipping configuration."
else
    # Insert source before_ohmyzsh.zsh line
    if grep -q "$SOURCE_OH_MY_ZSH_LINE" "$HOME/.zshrc"; then
        if ! grep -q "$SOURCE_BEFORE_OHMYZSH_LINE" "$HOME/.zshrc"; then
            ESCAPED_SOURCE_OH_MY_ZSH_LINE=$(echo "$SOURCE_OH_MY_ZSH_LINE" | sed 's/[\/&]/\\&/g')
            sed -i "/${ESCAPED_SOURCE_OH_MY_ZSH_LINE}/i ${SOURCE_BEFORE_OHMYZSH_LINE}" "$HOME/.zshrc"
            echo "Added source for ${SOURCE_BEFORE_OHMYZSH_LINE} to .zshrc before sourcing oh-my-zsh."
        else
            echo "Source for ${SOURCE_BEFORE_OHMYZSH_LINE} already exists in .zshrc."
        fi
    else
        echo "$SOURCE_OH_MY_ZSH_LINE not found in .zshrc"
    fi
fi

# ---- zsh syntax highlighting ----

SOURCE_LINE="source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
RCFILE="$HOME/.zshrc"

if [[ -f "$RCFILE" ]]; then
    sed -i "\#${SOURCE_LINE}#d" "$RCFILE"
    echo "$SOURCE_LINE" >> "$RCFILE"
    echo "Updated $RCFILE with the syntax-highlighting sourcing line."
else
    echo "Warning: $RCFILE does not exist. Skipping configuration."
fi

# ---- Create symlinks for config directories ----
CONFIG_DIRS=("fuzzel" "i3blocks" "kitty" "sway" "alacritty" "eza" "git")
for config_dir in "${CONFIG_DIRS[@]}"; do
    TARGET="$HOME/.config/$config_dir"
    SOURCE="$(pwd)/$config_dir"
    if [[ -L "$TARGET" && "$(readlink "$TARGET")" != "$SOURCE" ]]; then
        rm "$TARGET"
    fi
    if [[ ! -e "$TARGET" ]]; then
        ln -s "$SOURCE" "$TARGET"
        echo "Created symbolic link for $config_dir."
    else
        echo "Symbolic link for $config_dir already exists."
    fi
done

# ---- wallpapers ----

TARGET="$HOME/.wallpapers"
SOURCE="$(pwd)/wallpapers"

if [[ -L "$TARGET" ]]; then
    if [[ "$(readlink "$TARGET")" == "$SOURCE" ]]; then
        echo "Symbolic link for wallpapers already exists."
    else
        echo "$TARGET exists as a symlink to a different location, skipping."
    fi
elif [[ -e "$TARGET" ]]; then
    echo "$TARGET already exists as a directory, skipping."
else
    ln -s "$SOURCE" "$TARGET"
    echo "Created symbolic link for wallpapers."
fi
