#!/bin/bash

# ---- repo root check ----
if [ ! -d ".git" ]; then
    echo "Please run this script from the root directory of the dotfiles repository."
    exit 1
fi

if [[ $EUID -eq 0 ]]; then
    echo "Runing as sudo"

    if [[ -d "/etc/ly" ]]; then
        cp "$(pwd)/ly/config.ini" "/etc/ly/config.ini"
        echo "Ly config updated"
    fi

    if [[ -d "/etc/keyd" ]]; then
        cp "$(pwd)/keyd/default.conf" "/etc/keyd/default.conf"
        echo "keyd config updated"
    fi

    exit 0
fi

# ---- before oh my zsh script building ----

BEFORE_OHMYZSH_PATH="$(pwd)/zsh/before_ohmyzsh.zsh"

echo "# ---- before oh my zsh source in .zshrc (autogenerated by setup script) ----" > "$BEFORE_OHMYZSH_PATH"

DOTFILES_PATH_EXPORT="export DOTFILES_REPO_ROOT=$(pwd)"
echo "$DOTFILES_PATH_EXPORT" >> "$BEFORE_OHMYZSH_PATH"

# ---- Ensure .config directory exists ----
[ -d "$HOME/.config" ] || mkdir "$HOME/.config"

# ---- Create symlinks for config directories ----
CONFIG_DIRS=("fuzzel" "i3blocks" "kitty" "sway" "alacritty" "eza" "git" "ptpython" "yazi" "tmux" "swaync" "tealdeer" "helix" "macchina" "waybar" "mako" "starship" "xdg-desktop-portal-wlr")
for config_dir in "${CONFIG_DIRS[@]}"; do
    TARGET="$HOME/.config/$config_dir"
    SOURCE="$(pwd)/$config_dir"
    if [[ -L "$TARGET" && "$(readlink "$TARGET")" != "$SOURCE" ]]; then
        rm "$TARGET"
    fi
    if [[ ! -e "$TARGET" ]]; then
        ln -s "$SOURCE" "$TARGET"
        echo "Created symbolic link for $config_dir."
    else
        echo "Symbolic link for $config_dir already exists."
    fi
done

# ---- wallpapers ----

TARGET="$HOME/.wallpapers"
SOURCE="$(pwd)/wallpapers"

if [[ -L "$TARGET" ]]; then
    if [[ "$(readlink "$TARGET")" == "$SOURCE" ]]; then
        echo "Symbolic link for wallpapers already exists."
    else
        echo "$TARGET exists as a symlink to a different location, skipping."
    fi
elif [[ -e "$TARGET" ]]; then
    echo "$TARGET already exists as a directory, skipping."
else
    ln -s "$SOURCE" "$TARGET"
    echo "Created symbolic link for wallpapers."
fi

# ---- shell completions ----
SCRIPT_PATH="$PWD/zsh/zsh_custom/completions/_gh"
command -v gh >/dev/null 2>&1 && gh completion -s zsh > "$SCRIPT_PATH"

# ---- script symlinks ----

SCRIPTS_DIR="$(pwd)/scripts"
TARGET_DIR="$HOME/.local/bin"

mkdir -p "$TARGET_DIR"

for src in "$SCRIPTS_DIR"/*; do
    [ -f "$src" ] || continue
    [ -x "$src" ] || continue
    script_name="$(basename "$src")"
    target="$TARGET_DIR/$script_name"
    if [ -e "$target" ] || [ -L "$target" ]; then
        if [ -L "$target" ] && [ "$(readlink -- "$target")" = "$src" ]; then
            echo "Symlink for $script_name already exists and is correct. Skipping."
        else
            echo "WARNING: $target already exists and is not the correct symlink. Skipping."
        fi
    else
        ln -s "$src" "$target"
        echo "Created symlink: $target -> $src"
    fi
done
