---
- name: Installation playbok
  hosts: localhost
  become_method: ansible.builtin.sudo

  tasks:
    - name: Install fonts
      ansible.builtin.include_role:
        name: install_fonts
      vars:
        force_check: false
      tags: fonts

    - name: Add github cli apt repo
      ansible.builtin.include_role:
        name: add_apt_repository
      vars:
        repo_type: "deb"
        repo_url: "https://cli.github.com/packages"
        key_url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
        key_filename: "githubcli-archive-keyring.gpg"
        repo_distribution: "stable"
        repo_filename: "github-cli.list"
        components: ["main"]
      tags: apt_sources, shell_only

    - name: Add firefox apt repo
      ansible.builtin.include_role:
        name: add_apt_repository
      vars:
        repo_type: "deb"
        repo_url: "https://packages.mozilla.org/apt"
        key_url: "https://packages.mozilla.org/apt/repo-signing-key.gpg"
        key_filename: "packages.mozilla.org.asc"
        repo_distribution: "mozilla"
        repo_filename: "mozilla.list"
        components: ["main"]
      tags: apt_sources

    - name: Add docker apt repo
      ansible.builtin.include_role:
        name: add_apt_repository
      vars:
        repo_type: "deb"
        repo_url: "https://download.docker.com/linux/debian"
        key_url: "https://download.docker.com/linux/debian/gpg"
        key_filename: "docker.asc"
        repo_distribution: "bookworm"
        repo_filename: "docker.list"
        components: ["stable"]
      tags: apt_sources

    - name: Update local apt index files
      ansible.builtin.apt:
        update_cache: true
      become: true
      tags: apt_sources, packages_install, shell_only

    - name: Install dev command line tools
      ansible.builtin.apt:
        pkg:
          - zsh
          - htop
          - git
          - ripgrep
          - gh
          - pipx
          - bat
          - fd-find
          - zsh-syntax-highlighting
      become: true
      tags: packages_install, shell_only

    - name: Install apt packages - GUI
      ansible.builtin.apt:
        pkg:
          - sway
          - wl-clipboard
          - pulseaudio-utils
          - grimshot
          - kitty
          - firefox
      become: true
      tags: packages_install

    - name: Install oh my zsh
      ansible.builtin.include_role:
        name: install_oh_my_zsh
      vars:
        force_zshrc: true
      tags: oh_my_zsh, shell_only

    - name: Place configs
      ansible.builtin.include_role:
        name: configure_dotfiles
      tags: shell_only, dotfiles

    - name: Install fzf from archive
      ansible.builtin.include_role:
        name: install_from_archive
        apply:
          tags:
            - archive_bin
      vars:
        archive_url: "https://github.com/junegunn/fzf/releases/download/v0.62.0/fzf-0.62.0-linux_amd64.tar.gz"
        binary_path_from_extract: "fzf"
        expected_version: "0.62.0"
      tags: archive_bin

    - name: Install delta from archive
      ansible.builtin.include_role:
        name: install_from_archive
        apply:
          tags:
            - archive_bin
      vars:
        archive_url: "https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-unknown-linux-gnu.tar.gz"
        binary_path_from_extract: "delta-0.18.2-x86_64-unknown-linux-gnu/delta"
        expected_version: "0.18.2"
      tags: archive_bin
