---
- name: Installation playbok
  hosts: localhost
  become_method: sudo

  tasks:
    - name: Install fonts
      include_role:
        name: install_fonts
      vars:
        force_check: false
      tags: fonts

    - name: Add github cli apt repo
      include_role:
        name: add_apt_repository
      vars:
        repo_type: "deb"
        repo_url: "https://cli.github.com/packages"
        key_url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
        key_filename: "githubcli-archive-keyring.gpg"
        repo_distribution: "stable"
        repo_filename: "github-cli.list"
        components: ["main"]
      tags: apt_sources, shell_only

    - name: Add firefox apt repo
      include_role:
        name: add_apt_repository
      vars:
        repo_type: "deb"
        repo_url: "https://packages.mozilla.org/apt"
        key_url: "https://packages.mozilla.org/apt/repo-signing-key.gpg"
        key_filename: "packages.mozilla.org.asc"
        repo_distribution: "mozilla"
        repo_filename: "mozilla.list"
        components: ["main"]
      tags: apt_sources

    - name: Update local apt index files
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: apt_sources, packages_install, shell_only

    - name: Install dev command line tools
      ansible.builtin.apt:
        pkg:
        - zsh
        - htop
        - git
        - ripgrep
        - gh
        - pipx
        - bat
        - fd-find
        - git-delta
        - zsh-syntax-highlighting
      become: yes
      tags: packages_install, shell_only

    - name: Install apt packages - GUI
      ansible.builtin.apt:
        pkg:
        - sway
        - wl-clipboard
        - pulseaudio-utils
        - grimshot
        - kitty
        - firefox
      become: yes
      tags: packages_install

    - name: Install oh my zsh
      include_role:
        name: install_oh_my_zsh
      vars:
        zshrc_full_path: "{{ ansible_env.HOME }}/zshrc_temp"
        oh_my_zsh_directory: "{{ ansible_env.HOME }}/omz_temp"
        force_zshrc: true
        oh_my_zsh_theme: "fishy"
      tags: oh_my_zsh, shell_only
