theme = "ayu_dark"

[editor]
mouse = false
cursorline = true
bufferline="always"
line-number = "relative"
jump-label-alphabet = "sadjklewcmpgh"
# rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space]
q = ":quit"
"A-Q" = ":quit!"
"A-p" = ":sh pwd | tr -d '\n' | wl-copy"

[keys.normal]
"G" = "goto_last_line"
"A-x" = "extend_to_line_bounds"
"X" = "select_line_above"
"A-V" = ["goto_first_nonwhitespace", "extend_to_line_end"]
V = ["extend_to_line_end"]
"A-ret" = "vsplit"
"A-q" = ":quit"

"A-l" = "jump_view_right"
"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k"= "jump_view_up"
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-W" = ":buffer-close!"

"A-u" = "page_cursor_half_up"
"A-d" = "page_cursor_half_down"

[keys.normal.g]
"k" = "goto_next_change"
"j" = "goto_prev_change"
"o" = "goto_file_start"

[keys.select]
"A-x" = "extend_to_line_bounds"
"X" = "select_line_above"

"A-u" = "page_cursor_half_up"
"A-d" = "page_cursor_half_down"

V = ["extend_to_line_end"]

[keys.insert]
"A-l" = "jump_view_right"
"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k"= "jump_view_up"
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"

"A-u" = "page_cursor_half_up"
"A-d" = "page_cursor_half_down"

C-space = "signature_help"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true
