# before using this config:
# pipx inject python-lsp-server python-lsp-ruff python-lsp-black
# pipx install python-lsp-server
# pipx install ruff
[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = false
plugins.black.enabled = false

plugins.flake8.enabled = false
plugins.autopep8.enabled = false
plugins.mccabe.enabled = false
plugins.pycodestyle.enabled = false
plugins.pyflakes.enabled = false
plugins.pylint.enabled = false
plugins.yapf.enabled = false

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[[language]]
name = "python"
language-servers = [
  { name = "scls" },
  { name = "pylsp", except-features = ["format"] },
  { name = "pyrefly", only-features = ["diagnostics"] },
  { name = "ruff" },
]

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100
feature_words = true
feature_snippets = true
snippets_first = true
snippets_inline_by_word_tail = false
feature_unicode_input = false
feature_paths = false
feature_citations = false


[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = [
  "yml",
  "yaml",
  { glob = ".prettierrc" },
  { glob = ".clangd" },
  { glob = ".clang-format" },
  { glob = ".clang-tidy" },
  "sublime-syntax"
]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { name = "scls" },
  { name = "yaml-language-server", except-features = ["hover"]},
  { name = "ansible-language-server"}
]
injection-regex = "yml|yaml"

[[language]]
name = "git-commit"
formatter = { command = "fold", timeout = 5, args = ["-w", "72", "-s"]}
