---

- name: Check if .zshrc already exists
  ansible.builtin.stat:
    path: "{{ zshrc_full_path }}"
  register: zshrc_status
  tags: oh_my_zsh, shell_only

- name: Template zshrc file
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ zshrc_full_path }}"
    mode: "0644"
  when: not zshrc_status.stat.exists or force_zshrc
  tags: oh_my_zsh, shell_only

- name: Clone oh my zsh repo
  ansible.builtin.git:
    repo: "{{ oh_my_zsh_mirror }}"
    dest: "{{ oh_my_zsh_directory }}"
  environment:
      GIT_TERMINAL_PROMPT: 0
  tags: oh_my_zsh, shell_only
