configure_dotfiles_home_dir: "{{ ansible_env.HOME }}"
configure_dotfiles_repo_root: "{{ configure_dotfiles_home_dir }}/.dotfiles"
configure_dotfiles_repo_mirror: "https://github.com/piotr-ginal/dotfiles.git"
configure_dotfiles_config_directories: ["fuzzel",
                                        "i3blocks",
                                        "kitty",
                                        "sway",
                                        "alacritty",
                                        "eza",
                                        "git",
                                        "ptpython",
                                        "yazi",
                                        "tmux",
                                        "swaync",
                                        "tealdeer",
                                        "helix",
                                        "macchina",
                                        "waybar"]
configure_dotfiles_target_config_directory: "{{ configure_dotfiles_home_dir }}/.config"
configure_dotfiles_wallpaper_dir_link_dest: "{{ configure_dotfiles_home_dir }}/.wallpapers"
configure_dotfiles_before_omz_file_path: "{{ configure_dotfiles_repo_root }}/zsh/before_ohmyzsh.zsh"
configure_dotfiles_update_repo: false
configure_dotfiles_syntax_script_path: "/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
