---
- name: Filter urls
  stat:
    path: "{{ fonts_directory }}/{{ item | basename }}"
  register: url_check
  loop: "{{ ttf_urls }}"
  no_log: true

- name: Download fonts
  ansible.builtin.get_url:
    url: "{{ item.item }}"
    dest: "{{ fonts_directory }}/{{ item.item | basename }}"
  loop: "{{ url_check.results }}"
  when: not item.stat.exists or force_check
  retries: 3
  delay: 5
  no_log: true
