---
- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: "{{ fonts_directory }}"
    state: directory
    mode: "0751"
    recurse: true
  tags: fonts

- name: Install font config package
  ansible.builtin.apt:
    pkg: fontconfig
    update_cache: true
  become: true
  tags: fonts

- name: Filter urls
  ansible.builtin.stat:
    path: "{{ fonts_directory }}/{{ item | basename }}"
  register: url_check
  loop: "{{ ttf_urls }}"
  no_log: true
  tags: fonts

- name: Download fonts
  ansible.builtin.get_url:
    url: "{{ item.item }}"
    dest: "{{ fonts_directory }}/{{ item.item | basename }}"
    mode: "0644"
  loop: "{{ url_check.results }}"
  when: not item.stat.exists or force_check
  notify: Refresh font cache
  retries: 3
  delay: 5
  no_log: true
  tags: fonts
