---
home_dir: "{{ ansible_env.HOME }}"
oh_my_zsh_directory: "{{ home_dir }}/.oh-my-zsh"
oh_my_zsh_mirror: "https://github.com/ohmyzsh/ohmyzsh.git"
zshrc_full_path: "{{ home_dir }}/.zshrc"
oh_my_zsh_theme: "git-root-nor-green"
terminal_type: "xterm-256color"
force_zshrc: false
