#!/bin/bash

LIST=$(cat <<EOF
🔥; fire
💀; skull
🤑; money-mouth face
😂; face with tears of joy
🤣; rolling on the floor laughing
😹; cat with tears of joy
😆; grinning squinting face
😄; grinning face with smiling eyes
😃; grinning face with big eyes
😅; grinning face with sweat
😸; grinning cat face with smiling eyes
😭; loudly crying face emoji
😺; grinning cat face
😊; smiling face with smiling eyes
😁; beaming face with smiling eyes
😬; grimacing face
😏; smirking face
😋; face savoring food
😛; face with tongue
😝; squinting face with tongue
😜; winking face with tongue
🙂; slightly smiling face
😎; smiling face with sunglasses
☺️; smiling face
🥀; wilted rose
❤️; red heart
💙; blue heart
💚; green heart
💛; yellow heart
💜; purple heart
🖤; black heart
💗; growing heart
💖; sparkling heart
💕; two hearts
💔; broken heart
EOF
)

SELECTED=$(echo "$LIST" | fuzzel --dmenu | cut -d';' -f1 | tr -d ' ')

if [[ -n "$SELECTED" ]]; then
    wtype "$SELECTED"
fi
