#!/usr/bin/env bash

url="$1"

firefox_instance=$(swaymsg -t get_tree | jq -r '
    recurse(.nodes[]?, .floating_nodes[]?) |
    select(.app_id == "firefox" and .scratchpad_state == "none") |
    .id
' | head -n 1)

if [ -n "$firefox_instance" ]; then
    swaymsg "[con_id=$firefox_instance] focus"
    if [ -n "$url" ]; then
        swaymsg exec "firefox \"$url\""
    fi
else
    attempt_switch_to_empty_workspace_sway
    if [ -n "$url" ]; then
        swaymsg exec "firefox \"$url\""
    else
        swaymsg exec firefox
    fi
fi
