#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: opr <regex>"
    exit 1
fi

percentage="40"

if [ -n "$2" ]; then
    percentage="$2"
fi

regex="$1"

rg -i --no-heading --line-number "$regex" . | cut -d':' -f1-2 | sort | fzf \
    --preview "file=\$(echo {} | cut -d: -f1); \
               line=\$(echo {} | cut -d: -f2); \
               if [ -n \"\$line\" ]; then \
                   start_line=\$((line > 2 ? line - 2 : 1)); \
                   batcat --style=numbers --color=always --highlight-line=\$line \"\$file\" -r \$start_line:; \
               else \
                   echo 'No match found in preview'; \
               fi" \
    --layout=reverse \
    --bind "ctrl-d:preview-down,ctrl-u:preview-up" \
    --preview-window=up:${percentage}% \
    --bind "enter:execute(file=\$(echo {} | cut -d: -f1); \
            line=\$(echo {} | cut -d: -f2); \
            hx \"\$file\" +\$line)"
