#!/usr/bin/env bash

KEEPASSXC_DB_PATH="$HOME/.encrypted/passwords.kdbx"
CLIPBOARD_TIMEOUT=15


if [ ! -f "$KEEPASSXC_DB_PATH" ]; then
    echo >&2 "keepassxc db not found at '$KEEPASSXC_DB_PATH'"
    exit 1
fi

read -s -r -p "db passwd: " KEEPASSXC_PASSWORD_INPUT
echo

if [ -z "$KEEPASSXC_PASSWORD_INPUT" ]; then
    exit 1
fi

if ! echo "$KEEPASSXC_PASSWORD_INPUT" | keepassxc-cli ls "$KEEPASSXC_DB_PATH" &>/dev/null; then
    echo >&2 "failed to open database"
    exit 1
fi

SELECTED_ENTRY=$(echo "$KEEPASSXC_PASSWORD_INPUT" | keepassxc-cli ls -Rf "$KEEPASSXC_DB_PATH" 2>/dev/null | fzf --prompt="select password entry:" --height="${FZF_HEIGHT:-40%}" --border --cycle --reverse)

if [ -z "$SELECTED_ENTRY" ]; then
    exit 0
fi

if ! echo "$KEEPASSXC_PASSWORD_INPUT" | keepassxc-cli clip "$KEEPASSXC_DB_PATH" "$SELECTED_ENTRY" "$CLIPBOARD_TIMEOUT" &>/dev/null; then
    echo >&2 "failed to copy passw"
fi

exit 0
