#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "Usage: $0 <GOOGLE_SERVICE_BASE_URL>"
  exit 1
fi

GOOGLE_SERVICE_BASE_URL="$1"

# file format:
# foo@example.com;foo description
# bar@example.com;bar description
ACCOUNT_LIST_FILE="$HOME/.scriptfiles/gmail_accounts"

selected_user=$(column -t -s ';' "$ACCOUNT_LIST_FILE" | fzf --height=~40% | awk '{print $1}')

[ -n "$selected_user" ] && focus_or_open_firefox_sway "${GOOGLE_SERVICE_BASE_URL}?authuser=${selected_user}"
