#!/bin/bash

outputs=$(swaymsg -t get_outputs | jq -r '.[] | select(.active) | .name')

monitor1=$(echo "$outputs" | grep -v 'eDP-1' | sed -n '1p')
monitor2=$(echo "$outputs" | grep -v 'eDP-1' | sed -n '2p')
monitor3=$(echo "$outputs" | grep 'eDP-1')

echo "monitor 1: $monitor1"
echo "monitor 2: $monitor2"
echo "monitor 3: $monitor3"

if [ -n "$monitor1" ] && [ -z "$monitor2" ]; then
    swaymsg workspace 1 output $monitor1
    swaymsg workspace 2 output $monitor1
    swaymsg workspace 3 output $monitor1
    swaymsg workspace 4 output $monitor1
    swaymsg workspace 5 output $monitor1
    swaymsg workspace 6 output $monitor1
    swaymsg workspace 7 output $monitor3
    swaymsg workspace 8 output $monitor3
    swaymsg workspace 9 output $monitor3
else
    if [ -n "$monitor1" ]; then
        swaymsg workspace 1 output $monitor1
        swaymsg workspace 2 output $monitor1
        swaymsg workspace 3 output $monitor1
    fi

    if [ -n "$monitor2" ]; then
        swaymsg workspace 4 output $monitor2
        swaymsg workspace 5 output $monitor2
        swaymsg workspace 6 output $monitor2
    fi

    if [ -n "$monitor3" ]; then
        swaymsg workspace 7 output $monitor3
        swaymsg workspace 8 output $monitor3
        swaymsg workspace 9 output $monitor3
    fi
fi
