set -g default-terminal "screen-256color"
set -sa terminal-overrides ",alacritty*:Tc"
set -g escape-time 0
set -g mouse on
set -g renumber-windows on
set -g repeat-time 1000

set -g base-index 1
set -g pane-base-index 1

unbind C-b
set -g prefix `
bind ` send-prefix

set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=white

set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}%H:%M %d.%m"

set -g window-status-style "fg=#BFBDB6,nobold"

set -g window-status-current-style "fg=#20AFC1,nobold"

set -g window-status-bell-style "fg=red,nobold"

bind k select-pane -U
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R

bind -r K resize-pane -U
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r L resize-pane -R

bind q kill-pane

bind b split-window -h
bind v split-window -v

bind -n C-Tab next-window
bind -n C-S-Tab previous-window

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Escape send-keys -X cancel

set-option -g history-limit 10000

set -as command-alias "rn=rename-window"
